# Generated by Django 5.0.7 on 2026-05-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر ربات', 'verbose_name_plural': 'کاربران ربات'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='شناسه چت'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_registered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ثبت\u200cنام کامل شده؟'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='registered_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام واردشده در ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای وضعیت'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='bale_user_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='شناسه کاربر در بله'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام در بله'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین است؟'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مسدود شده؟'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی در بله'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین بازدید'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_state',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='آخرین وضعیت'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['bale_user_id'], name='users_botus_bale_us_e26245_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['chat_id'], name='users_botus_chat_id_f0dcab_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['phone_number'], name='users_botus_phone_n_ac3509_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['is_registered'], name='users_botus_is_regi_12e54d_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['last_seen_at'], name='users_botus_last_se_87dd8d_idx'),
        ),
    ]
