# Generated by Django 6.0.4 on 2026-05-10 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], db_index=True, default='info', max_length=20, verbose_name='Log Level')),
                ('event_type', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_requested', 'Payment Requested'), ('gateway_redirect', 'Gateway Redirect'), ('callback_received', 'Callback Received'), ('verify_requested', 'Verify Requested'), ('verify_success', 'Verify Success'), ('verify_failed', 'Verify Failed'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('gateway_error', 'Gateway Error'), ('system_error', 'System Error')], db_index=True, max_length=50, verbose_name='Event Type')),
                ('gateway', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Gateway')),
                ('message', models.TextField(verbose_name='Message')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Authority / Token')),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Reference ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Tracking Code')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Extra Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='billing_pay_user_id_2d696f_idx'), models.Index(fields=['event_type', 'created_at'], name='billing_pay_event_t_9969c8_idx'), models.Index(fields=['level', 'created_at'], name='billing_pay_level_00904d_idx'), models.Index(fields=['gateway', 'created_at'], name='billing_pay_gateway_45ab89_idx'), models.Index(fields=['authority'], name='billing_pay_authori_3399b2_idx')],
            },
        ),
    ]
