# Generated by Django 6.0.4 on 2026-05-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('item_added', 'Item Added'), ('item_removed', 'Item Removed'), ('price_changed', 'Price Changed'), ('discount_applied', 'Discount Applied'), ('payment_attached', 'Payment Attached'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, max_length=50)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System'), ('gateway', 'Gateway'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, db_index=True, help_text='Temporary order number/reference until Order model exists.', max_length=100, null=True)),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('previous_status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('new_status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, help_text='Store changed fields, previous values and new values.', null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Log',
                'verbose_name_plural': 'Order Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='billing_ord_user_id_d25fad_idx'), models.Index(fields=['level', 'created_at'], name='billing_ord_level_28eb53_idx'), models.Index(fields=['event_type', 'created_at'], name='billing_ord_event_t_bf457f_idx'), models.Index(fields=['actor_type', 'created_at'], name='billing_ord_actor_t_6ebc8e_idx'), models.Index(fields=['order_number'], name='billing_ord_order_n_ea6f2f_idx'), models.Index(fields=['tracking_code'], name='billing_ord_trackin_2e58f5_idx'), models.Index(fields=['previous_status'], name='billing_ord_previou_2c489d_idx'), models.Index(fields=['new_status'], name='billing_ord_new_sta_f9eb8a_idx')],
            },
        ),
    ]
