# Generated by Django 6.0.4 on 2026-05-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_orderlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=32)),
                ('product_id', models.CharField(db_index=True, max_length=128)),
                ('product_data', models.JSONField(blank=True, default=dict)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده'), ('refunded', 'مرجوع شده')], db_index=True, default='pending', max_length=32)),
                ('tracking_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('card_to_card', 'کارت به کارت'), ('bale_wallet', 'کیف پول بله')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('init', 'ایجاد اولیه'), ('pending', 'در انتظار پرداخت'), ('waiting_for_receipt', 'در انتظار رسید'), ('waiting_for_review', 'در انتظار بررسی'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده'), ('rejected', 'رد شده')], db_index=True, default='init', max_length=32)),
                ('manual_review_status', models.CharField(choices=[('none', 'بدون بررسی'), ('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='none', max_length=32)),
                ('product_id', models.CharField(db_index=True, max_length=128)),
                ('product_data', models.JSONField(blank=True, default=dict)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payment_url', models.URLField(blank=True, max_length=1000)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('card_pan', models.CharField(blank=True, max_length=64)),
                ('fee_type', models.CharField(blank=True, max_length=64)),
                ('fee', models.PositiveBigIntegerField(blank=True, null=True)),
                ('destination_card_number', models.CharField(blank=True, max_length=32)),
                ('destination_card_owner', models.CharField(blank=True, max_length=255)),
                ('receipt_image', models.FileField(blank=True, null=True, upload_to='billing/card_to_card_receipts/')),
                ('receipt_file_id', models.CharField(blank=True, max_length=255)),
                ('receipt_tracking_code', models.CharField(blank=True, max_length=255)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('wallet_user_id', models.CharField(blank=True, max_length=255)),
                ('wallet_payload', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('request_response', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('verify_payload', models.JSONField(blank=True, default=dict)),
                ('verify_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_user_id_d25fad_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_level_28eb53_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_event_t_bf457f_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_actor_t_6ebc8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_order_n_ea6f2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_trackin_2e58f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_previou_2c489d_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='billing_ord_new_sta_f9eb8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='billing_pay_user_id_2d696f_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='billing_pay_event_t_9969c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='billing_pay_level_00904d_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='billing_pay_gateway_45ab89_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='billing_pay_authori_3399b2_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_billing_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='billing.payment'),
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='user',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='billing_pay_gateway_d18956_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['product_id'], name='billing_pay_product_35cfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['authority'], name='billing_pay_authori_5968fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ref_id'], name='billing_pay_ref_id_9a4f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['wallet_transaction_id'], name='billing_pay_wallet__213308_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='billing_ord_status_24593c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product_id'], name='billing_ord_product_4439a5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_code'], name='billing_ord_trackin_ec09f7_idx'),
        ),
        migrations.DeleteModel(
            name='OrderLog',
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
    ]
