# Generated by Django 6.0.4 on 2026-05-12 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_authori_5968fd_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='authority',
            new_name='trackId',
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('zibal', 'زیبال'), ('card_to_card', 'کارت به کارت'), ('bale_wallet', 'کیف پول بله')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['trackId'], name='billing_pay_trackId_3f1ba7_idx'),
        ),
    ]
