# Generated by Django 6.0.4 on 2026-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_baleprofile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='baleprofile',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
