# Generated by Django 6.0.4 on 2026-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_baleprofile_is_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baleprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
