# Generated by Django 6.0.4 on 2026-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_registration_compeleted',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(default='09123456789', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
