# Generated by Django 6.0.4 on 2026-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_managers_remove_accounts_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
