# Generated by Django 6.0.4 on 2026-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_registration_completed',
            field=models.BooleanField(default=False),
        ),
    ]
