# Generated by Django 6.0.4 on 2026-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
