# Generated by Django 6.0.4 on 2026-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_bot_bale_member',
            field=models.BooleanField(default=False),
        ),
    ]
