# Generated by Django 6.0.4 on 2026-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_is_bot_bale_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_company_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_jobseeker_member',
            field=models.BooleanField(default=False),
        ),
    ]
