# Generated by Django 6.0.4 on 2026-05-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounts_is_company_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
    ]
