# Generated by Django 6.0.4 on 2026-05-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounts_is_company_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
        migrations.AddField(
            model_name='accounts',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='day_birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='month_birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='year_birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره همراه'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.city', verbose_name='شهر'),
        ),
    ]
