# Generated by Django 6.0.4 on 2026-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_accounts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='day_birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='month_birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='year_birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره همراه'),
        ),
    ]
