# Generated by Django 6.0.4 on 2026-05-04 13:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, choices=[('tehran', 'تهران'), ('alborz', 'البرز'), ('yazd', 'یزد'), ('ahvaz', 'اهواز'), ('mazandaran', 'مازندران'), ('kerman', 'کرمان'), ('mashhad', 'مشهد'), ('gilan', 'گیلان'), ('shiraz', 'شیراز'), ('tabriz', 'تبریز'), ('qazvin', 'قزوین'), ('other', 'سایر')], max_length=20, null=True)),
                ('day_birthdate', models.IntegerField(blank=True, null=True)),
                ('month_birthdate', models.IntegerField(blank=True, null=True)),
                ('year_birthdate', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_enthusiasts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('management', 'حوزه مدیریت'), ('sales_marketing', 'حوزه فروش و بازاریابی'), ('support', 'حوزه پشتیبانی'), ('digital', 'حوزه دیجیتال'), ('finance_admin', 'حوزه مالی و اداری'), ('other', 'سایر')], max_length=30, null=True))),
                ('salary_range', models.CharField(blank=True, choices=[('20_30', '۲۰ تا ۳۰ میلیون'), ('30_40', '۳۰ تا ۴۰ میلیون'), ('40_50', '۴۰ تا ۵۰ میلیون'), ('50_60', '۵۰ تا ۶۰ میلیون'), ('60_70', '۶۰ تا ۷۰ میلیون'), ('70_80', '۷۰ تا ۸۰ میلیون')], max_length=10, null=True)),
                ('work_location_priority', models.CharField(blank=True, choices=[('city_center', 'مرکز شهر'), ('north', 'شمال شهر'), ('west', 'غرب'), ('east', 'شرق'), ('south', 'جنوب'), ('suburb', 'حومه')], max_length=20, null=True)),
                ('campaign_request', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('messenger', 'ارسال پیام\u200cرسان (واتساپ، تلگرام، موبایل بله)'), ('email', 'ارسال ایمیل'), ('sms', 'ارسال پیامک'), ('push_notification', 'ارسال پوش نوتیفیکیت'), ('jobex_channels', 'کانال\u200cهای ارتباطی جابکس'), ('combined', 'ترکیب (بالاترین بازخورد)')], max_length=30, null=True))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
