# Generated by Django 6.0.4 on 2026-05-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_size', models.CharField(blank=True, choices=[('5_50', '۵ تا ۵۰ نفر'), ('50_100', '۵۰ تا ۱۰۰ نفر'), ('200_500', '۲۰۰ تا ۵۰۰ نفر'), ('500_plus', '۵۰۰ نفر به بالا')], max_length=20, null=True, verbose_name='ابعاد سازمان')),
                ('city', models.CharField(blank=True, choices=[('tehran', 'تهران'), ('alborz', 'البرز'), ('yazd', 'یزد'), ('ahvaz', 'اهواز'), ('mazandaran', 'مازندران'), ('kerman', 'کرمان'), ('mashhad', 'مشهد'), ('gilan', 'گیلان'), ('shiraz', 'شیراز'), ('tabriz', 'تبریز'), ('qazvin', 'قزوین'), ('other', 'سایر')], max_length=20, null=True)),
                ('industry', models.CharField(max_length=255, verbose_name='صنعت/حوزه فعالیت سازمان')),
                ('full_address', models.TextField(verbose_name='آدرس کامل سازمان')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وب سایت سازمان')),
                ('landline_phone', models.CharField(max_length=20, verbose_name='شماره تلفن ثابت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل شرکت',
                'verbose_name_plural': 'پروفایل شرکت\u200cها',
            },
        ),
    ]
