# Generated by Django 6.0.4 on 2026-05-04 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='work_enthusiasts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('management', 'حوزه مدیریت'), ('sales_marketing', 'حوزه فروش و بازاریابی'), ('support', 'حوزه پشتیبانی'), ('digital', 'حوزه دیجیتال'), ('finance_admin', 'حوزه مالی و اداری'), ('other', 'سایر')], default=[''], max_length=30, null=True)),
        ),
    ]
