# Generated by Django 6.0.4 on 2026-05-04 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_jobseekerprofile_work_enthusiasts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='campaign_request',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('messenger', 'ارسال پیام\u200cرسان (واتساپ، تلگرام، موبایل بله)'), ('email', 'ارسال ایمیل'), ('sms', 'ارسال پیامک'), ('push_notification', 'ارسال پوش نوتیفیکیت'), ('jobex_channels', 'کانال\u200cهای ارتباطی جابکس'), ('combined', 'ترکیب (بالاترین بازخورد)')], default=list, max_length=30, null=True)),
        ),
    ]
