# Generated by Django 6.0.4 on 2026-05-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_jobseekerprofile_campaign_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('sales_marketing_specialist_manager', 'فروش و بازاریابی - کارشناس و مدیریت'), ('direct_sales_marketer_visitor', 'فروش مستقیم - بازاریاب - ویزیتور'), ('customer_service_support', 'خدمات و پشتیبانی مشتریان'), ('graphic_motion_photography', 'گرافیک - موشن - عکاسی'), ('ui_ux_design', 'طراحی رابط کاربری (UI-UX)'), ('product_manager_owner', 'مدیر محصول - مالک محصول'), ('software_development_programming', 'توسعه نرم افزار و برنامه نویسی'), ('network_hardware_software_support', 'شبکه - پشتیبانی سخت افزار یا نرم افزار'), ('artificial_intelligence', 'هوش مصنوعی'), ('finance_accounting', 'مالی - حسابداری'), ('executive_internal_manager', 'مدیر اجرایی و مدیر داخلی'), ('office_admin_employee', 'مسئول دفتر - کارمند اداری'), ('medical_representative', 'نماینده علمی/مدرپ'), ('human_resources', 'منابع انسانی'), ('content_production', 'تولید محتوا'), ('public_relations', 'روابط عمومی'), ('social_media', 'شبکه\u200cهای اجتماعی'), ('business_strategy_development_analysis', 'تحلیل توسعه استراتژی کسب و کار')], max_length=100, verbose_name='عنوان شغلی')),
                ('cooperation_type', models.CharField(choices=[('full_time', 'تمام\u200cوقت'), ('part_time', 'پاره\u200cوقت'), ('remote', 'دورکار')], max_length=20, verbose_name='نوع همکاری')),
                ('degree', models.CharField(blank=True, choices=[('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, null=True)),
                ('minimum_work_experience', models.CharField(choices=[('intern', 'کارآموز'), ('1_to_3_years', '1 تا 3 سال'), ('3_to_5_years', '3 تا 5 سال'), ('5_to_7_years', '5 تا 7 سال'), ('more_than_7_years', 'بیشتر')], max_length=30, verbose_name='حداقل سابقه کاری')),
                ('required_skills', models.TextField(verbose_name='مهارت\u200cهای الزامی')),
                ('job_description', models.TextField(verbose_name='شرح وظایف شغلی')),
                ('attendance_type', models.CharField(choices=[('on_site', 'مستقر'), ('mission', 'مأموریت'), ('remote', 'دورکار')], max_length=30, verbose_name='نحوه حضور')),
                ('working_days', models.CharField(choices=[('saturday_to_wednesday', 'شنبه تا چهارشنبه'), ('saturday_to_thursday', 'شنبه تا پنجشنبه'), ('total_working_hours', 'مجموع ساعت کار')], max_length=40, verbose_name='روزهای کاری')),
                ('has_overtime', models.BooleanField(default=False, verbose_name='اضافه\u200cکار دارد؟')),
                ('working_hours', models.CharField(choices=[('8_to_16', '8 تا 16'), ('9_to_17', '9 تا 17'), ('other', 'سایر')], max_length=20, verbose_name='ساعات کاری')),
                ('working_hours_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح ساعات کاری')),
                ('is_salary_negotiable', models.BooleanField(default=False, verbose_name='حقوق توافقی است؟')),
                ('salary_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات حقوق')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='مزایا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='crm.companyprofile', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'آگهی شغلی',
                'verbose_name_plural': 'آگهی\u200cهای شغلی',
            },
        ),
    ]
