# Generated by Django 6.0.4 on 2026-05-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_registration_complete',
            field=models.BooleanField(default=False, verbose_name='ثبت\u200cنام کامل شده'),
        ),
    ]
