# Generated by Django 6.0.4 on 2026-05-15 06:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_city_remove_accounts_username_and_more'),
        ('crm', '0007_companyprofile_is_registration_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'verbose_name': 'پروفایل کارجو', 'verbose_name_plural': 'پروفایل کارجویان'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='campaign_request',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='day_birthdate',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='month_birthdate',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='year_birthdate',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='accounts.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل شرکت'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس وب\u200cسایت سازمان'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('20_30', '۲۰ تا ۳۰ میلیون'), ('30_40', '۳۰ تا ۴۰ میلیون'), ('40_50', '۴۰ تا ۵۰ میلیون'), ('50_60', '۵۰ تا ۶۰ میلیون'), ('60_70', '۶۰ تا ۷۰ میلیون'), ('70_80', '۷۰ تا ۸۰ میلیون')], max_length=10, verbose_name='بازه حقوق درخواستی'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='work_enthusiasts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('management', 'حوزه مدیریت'), ('sales_marketing', 'حوزه فروش و بازاریابی'), ('support', 'حوزه پشتیبانی'), ('digital', 'حوزه دیجیتال'), ('finance_admin', 'حوزه مالی و اداری'), ('other', 'سایر')], max_length=30), blank=True, default=list, verbose_name='علاقه\u200cمندی\u200cهای شغلی'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='work_location_priority',
            field=models.CharField(blank=True, choices=[('city_center', 'مرکز شهر'), ('north', 'شمال شهر'), ('west', 'غرب'), ('east', 'شرق'), ('south', 'جنوب'), ('suburb', 'حومه')], max_length=20, verbose_name='اولویت محل کار'),
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('admin', 'ادمین'), ('hr', 'منابع انسانی'), ('recruiter', 'استخدام'), ('member', 'عضو')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='crm.companymembership', verbose_name='عضویت شرکت'),
        ),
    ]
