# Generated by Django 6.0.4 on 2026-05-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_jobseekerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='کلید')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کانال اطلاع\u200cرسانی',
                'verbose_name_plural': 'کانال\u200cهای اطلاع\u200cرسانی',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfileCampaignChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('campaign_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile_links', to='crm.campaignchannel', verbose_name='کانال اطلاع\u200cرسانی')),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_campaign_channels', to='crm.jobseekerprofile', verbose_name='پروفایل کارجو')),
            ],
            options={
                'verbose_name': 'کانال اطلاع\u200cرسانی پروفایل کارجو',
                'verbose_name_plural': 'کانال\u200cهای اطلاع\u200cرسانی پروفایل\u200cهای کارجو',
                'unique_together': {('job_seeker_profile', 'campaign_channel')},
            },
        ),
    ]
