# Generated by Django 6.0.4 on 2026-05-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_campaignchannel_jobseekerprofilecampaignchannel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobseekerprofilecampaignchannel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobseekerprofilecampaignchannel',
            name='status',
            field=models.CharField(choices=[('user_request', 'درخواست کاربر'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('sent', 'ارسال شده')], default='user_request', max_length=20, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterUniqueTogether(
            name='jobseekerprofilecampaignchannel',
            unique_together={('job_seeker_profile', 'campaign_channel', 'status')},
        ),
    ]
