# Generated by Django 6.0.4 on 2026-05-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_jobseekerprofilecampaignchannel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.companyrole'),
        ),
    ]
