# Generated by Django 6.0.4 on 2026-05-17 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_companyrole_remove_companyprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='crm.companymembership', verbose_name='عضویت شرکت'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_membership'),
        ),
    ]
