# Generated by Django 6.0.4 on 2026-05-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_companymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='created_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to='crm.companymembership', verbose_name='ایجادکننده آگهی'),
        ),
    ]
