# Generated by Django 6.0.4 on 2026-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_jobposting_created_by_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه فایل رزومه در تلگرام'),
        ),
    ]
